// script.js
function sendMessage() {
    var userMessage = document.getElementById("user_input").value;
    // Display user message in chatbox
    // ...
    // Send userMessage to app.py (using AJAX or fetch)
    // ...
    // Receive response from app.py
    // ...
    // Display chatbot response in chatbox
    // ...
    // Store messages in text.txt (you might need server-side help)
    // ...
}
